Repository aws/s2n-tls, pull requests merged in 2019-12, with the labels that each got.

#1272 TLS 1.3 Handshake and Key Integration
  tests/unit/s2n_server_key_share_extension_test.c
  tests/unit/s2n_tls13_handshake_test.c
  tests/unit/s2n_tls13_record_aead_test.c
  tests/unit/s2n_tls13_state_machine_handshake_test.c
  tls/s2n_handshake_io.c
  tls/s2n_record_read.c
  tls/s2n_record_write.c
  tls/s2n_tls13_handshake.c
  tls/s2n_tls13_handshake.h
Labels: type/tls_1.3

#1256 Update s2n_handshake_io.saw to prove TLS1.3
  .travis/s2n_travis_build.sh
  tests/saw/spec/handshake/handshake_io_lowlevel.saw
  tests/saw/spec/handshake/rfc-handshake.cry
  tests/saw/spec/handshake/s2n_handshake_io.cry
  tls/s2n_handshake.h
  tls/s2n_handshake_io.c
Labels: type/formal_verification

#1320 Rename symbols in SIKE R1 code to avoid future naming/linking conflicts
  CMakeLists.txt
  pq-crypto/sike_r1/Makefile
  pq-crypto/sike_r1/P503_internal_r1.h
  pq-crypto/sike_r1/P503_r1.c
  pq-crypto/sike_r1/api_r1.h
  pq-crypto/sike_r1/config_r1.h
  pq-crypto/sike_r1/ec_isogeny_r1.c
  pq-crypto/sike_r1/fips202_r1.c
  pq-crypto/sike_r1/fips202_r1.h
  pq-crypto/sike_r1/fp_generic_r1.c
  pq-crypto/sike_r1/fpx_r1.c
  pq-crypto/sike_r1/sidh_r1.c
  pq-crypto/sike_r1/sike_p503_r1_kem.c
  pq-crypto/sike_r1/sike_p503_r1_kem.h
  pq-crypto/sike_r1/sike_r1_namespace.h
  tests/saw/Makefile
  tests/saw/sike/patch/api_r1.h.mod
  tests/saw/sike/patch/api_r1.h.orig
  tests/saw/sike/patch/api_r1.h.patch
  tests/saw/sike/patch/ec_isogeny_r1.c.mod
  tests/saw/sike/patch/ec_isogeny_r1.c.orig
  tests/saw/sike/patch/ec_isogeny_r1.c.patch
  tests/saw/sike/patch/sidh_r1.c.mod
  tests/saw/sike/patch/sidh_r1.c.orig
  tests/saw/sike/patch/sidh_r1.c.patch
  tests/saw/sike/proof/cshake.saw
  tests/saw/sike/proof/curv.saw
  tests/saw/sike/proof/field.saw
  tests/saw/sike/proof/isogeny.saw
  tests/saw/sike/proof/sidh.saw
  tests/saw/sike/proof/word.saw
Labels: type/post-quantum
