Repository aws/s2n-tls, pull requests merged in 2020-11, with the labels that each got.

#2330 FindLibCrypto.cmake is easier to consume.
  CMakeLists.txt
  cmake/s2n-config.cmake
Labels: type/build

#2369 ci: Add well_known_endpoints to the Omnibus job
  codebuild/spec/buildspec_omnibus.yml
Labels: type/build

#2362 ci: CodeBuild scripts to support AL2
  codebuild/bin/install_al2_dependencies.sh
  codebuild/bin/install_default_dependencies.sh
  codebuild/bin/install_gnutls.sh
  codebuild/bin/install_shellcheck.sh
  codebuild/bin/install_sslyze.sh
  codebuild/bin/s2n_setup_env.sh
  codebuild/spec/buildspec_amazonlinux2.yml
  tests/integration/Makefile
Labels: type/build

#2386 Remove hash state from s2n_map
  utils/s2n_map.c
  utils/s2n_map.h
  utils/s2n_map_internal.h
Labels: type/bug

#2388 Update well known endpoint test with new PQ KMS ciphers
  tests/integrationv2/common.py
  tests/integrationv2/providers.py
  tests/integrationv2/test_well_known_endpoints.py
Labels: type/post-quantum
