Repository aws/s2n-tls, pull requests merged in 2020-05, with the labels that each got.

#1845 Fix the s2n_stuffer_wipe_n proof to work with the new flags
  error/s2n_errno.h
  tests/cbmc/proofs/s2n_stuffer_wipe_n/s2n_stuffer_wipe_n_harness.c
  utils/s2n_blob.c
Labels: CBMC

#1849 Fixes uninitialized stuffer error
  tests/unit/s2n_extension_type_test.c
Labels: type/bug

#1885 Changes the name of struct s2n_kem_keypair -> s2n_kem_params
  tests/fuzz/s2n_bike_r1_fuzz_test.c
  tests/fuzz/s2n_bike_r2_fuzz_test.c
  tests/fuzz/s2n_client_key_recv_fuzz_test.c
  tests/fuzz/s2n_hybrid_ecdhe_bike_r1_fuzz_test.c
  tests/fuzz/s2n_hybrid_ecdhe_bike_r2_fuzz_test.c
  tests/fuzz/s2n_hybrid_ecdhe_sike_r1_fuzz_test.c
  tests/fuzz/s2n_hybrid_ecdhe_sike_r2_fuzz_test.c
  tests/fuzz/s2n_sike_r1_fuzz_test.c
  tests/fuzz/s2n_sike_r2_fuzz_test.c
  tests/testlib/s2n_hybrid_kem_tests.c
  tests/unit/s2n_client_extensions_test.c
  tests/unit/s2n_kem_test.c
  tests/unit/s2n_kex_with_kem_test.c
  tls/s2n_client_key_exchange.c
  tls/s2n_connection.c
  tls/s2n_crypto.h
  tls/s2n_kem.c
  tls/s2n_kem.h
  tls/s2n_kex.c
  tls/s2n_server_key_exchange.c
Labels: type/post-quantum

#1836 Pr issue templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ops-backlog

#1627 style: Reformatting with clang-format
  .clang-format
  .gitignore
  codebuild/bin/format.sh
  error/s2n_errno.c
  error/s2n_errno.h
  tls/s2n_cipher_preferences.c
  tls/s2n_handshake_io.c
Labels: status/needs_team_discussion

#1874 Key Update Receive
  crypto/s2n_tls13_keys.c
  crypto/s2n_tls13_keys.h
  tests/integration/s2n_tls13_handshake_tests.py
  tests/unit/s2n_key_update_test.c
  tls/s2n_connection.h
  tls/s2n_crypto.h
  tls/s2n_handshake.h
  tls/s2n_key_update.c
  tls/s2n_key_update.h
  tls/s2n_post_handshake.c
  tls/s2n_post_handshake.h
  tls/s2n_recv.c
  tls/s2n_tls13_handshake.c
  tls/s2n_tls13_handshake.h
Labels: type/tls_1.3

#1888 Add shared secret blob to s2n_kem_params
  tests/fuzz/s2n_bike_r1_fuzz_test.c
  tests/fuzz/s2n_bike_r2_fuzz_test.c
  tests/fuzz/s2n_sike_r1_fuzz_test.c
  tests/fuzz/s2n_sike_r2_fuzz_test.c
  tests/unit/s2n_kem_test.c
  tests/unit/s2n_kex_with_kem_test.c
  tests/viz/s2n_state_machine_viz
  tls/s2n_client_key_exchange.c
  tls/s2n_crypto.h
  tls/s2n_kem.c
  tls/s2n_kem.h
  tls/s2n_server_key_exchange.c
  utils/s2n_mem.c
  utils/s2n_mem.h
Labels: type/post-quantum

#1842 Allow cbmc-batch.yaml to be clobbered at CI time
  tests/cbmc/proofs/Makefile.common
  tests/cbmc/proofs/prepare.py
  tests/cbmc/proofs/s2n_stuffer_alloc/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_copy/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_erase_and_read/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_erase_and_read_bytes/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_free/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_init/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_raw_read/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_raw_read/s2n_stuffer_raw_read_harness.c
  tests/cbmc/proofs/s2n_stuffer_read/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_read_bytes/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_reread/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_skip_read/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_wipe/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_wipe_n/cbmc-batch.yaml
Labels: CBMC

#1942 Do not check CBMC properties during coverage check
  tests/cbmc/proofs/Makefile.cbmc_batch
  tests/cbmc/proofs/Makefile.common
  tests/cbmc/proofs/s2n_stuffer_alloc/Makefile
  tests/cbmc/proofs/s2n_stuffer_copy/Makefile
  tests/cbmc/proofs/s2n_stuffer_erase_and_read/Makefile
  tests/cbmc/proofs/s2n_stuffer_erase_and_read_bytes/Makefile
  tests/cbmc/proofs/s2n_stuffer_free/Makefile
  tests/cbmc/proofs/s2n_stuffer_init/Makefile
  tests/cbmc/proofs/s2n_stuffer_raw_read/Makefile
  tests/cbmc/proofs/s2n_stuffer_read/Makefile
  tests/cbmc/proofs/s2n_stuffer_read_bytes/Makefile
  tests/cbmc/proofs/s2n_stuffer_reread/Makefile
  tests/cbmc/proofs/s2n_stuffer_skip_read/Makefile
  tests/cbmc/proofs/s2n_stuffer_wipe/Makefile
  tests/cbmc/proofs/s2n_stuffer_wipe_n/Makefile
Labels: CBMC

#1922 Add generalized KEM public_key/ciphertext send/receive functions
  tests/unit/s2n_kem_test.c
  tls/s2n_client_key_exchange.c
  tls/s2n_kem.c
  tls/s2n_kem.h
  tls/s2n_server_key_exchange.c
  tls/s2n_tls_parameters.h
Labels: type/post-quantum
