Repository aws/s2n-tls, pull requests merged in 2020-01, with the labels that each got.

#1366 Update pq-crypto/README.md for SIKE round 2
  pq-crypto/README.md
Labels: type/post-quantum

#1363 Use optimized SIKE round 2 assembly code for x86_64
  .travis.yml
  .travis/s2n_setup_env.sh
  CMakeLists.txt
  pq-crypto/sike_r2/Makefile
  pq-crypto/sike_r2/P434.c
  pq-crypto/sike_r2/config.h
  pq-crypto/sike_r2/fp_generic.c
  pq-crypto/sike_r2/fp_x64.c
  pq-crypto/sike_r2/fp_x64_asm.S
  pq-crypto/sike_r2/sike_r2_code_identifier.h
  s2n.mk
  tests/unit/s2n_sike_r2_verify_included_code_test.c
Labels: type/post-quantum

#1370 Add fuzz test for SIKE round 2 standalone (no ECDHE hybrid)
  tests/fuzz/corpus/s2n_sike_r2_fuzz_test/2f0f6807a5e3f49a3e33c56b95009caab890dc04
  tests/fuzz/corpus/s2n_sike_r2_fuzz_test/7f56381b251a07eb48cba627645bfe6bd7128a3c
  tests/fuzz/corpus/s2n_sike_r2_fuzz_test/valid_ciphertext
  tests/fuzz/s2n_sike_r2_fuzz_test.c
Labels: type/post-quantum

#1381 Additional sike_r1 symbol renaming
  Makefile
  pq-crypto/Makefile
  tests/saw/Makefile
Labels: type/post-quantum

#1390 Refactor PQ KEM hybrid ECDHE test for better abstracted functionality
  tests/testlib/s2n_hybrid_kem_tests.c
  tests/testlib/s2n_testlib.h
  tests/unit/s2n_hybrid_ecdhe_sike_p503_r1.c
  tests/unit/s2n_hybrid_ecdhe_sike_test.c
Labels: type/post-quantum

#1405 Refactor the hybrid PRF test to use a KAT file; add SIKE p434 known answers
  tests/unit/kats/hybrid_prf.kat
  tests/unit/s2n_tls_hybrid_prf_test.c
Labels: type/post-quantum

#1374 Enable use of S2N_NO_PQ_ASM flag; disable PQ assembly code for Darwin/osx
  .travis.yml
  .travis/s2n_setup_env.sh
  CMakeLists.txt
  pq-crypto/sike_r2/Makefile
  pq-crypto/sike_r2/P434.c
  pq-crypto/sike_r2/config.h
  pq-crypto/sike_r2/fpx.c
  pq-crypto/sike_r2/sike_r2_code_identifier.h
  s2n.mk
  tests/unit/s2n_sike_r2_verify_included_code_test.c
Labels: type/post-quantum

#1422 CBMC proofs for s2n_stuffer_wipe() and s2n_stuffer_wipe_n()
  tests/cbmc/proofs/s2n_stuffer_wipe/Makefile
  tests/cbmc/proofs/s2n_stuffer_wipe/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_wipe/s2n_stuffer_wipe_harness.c
  tests/cbmc/proofs/s2n_stuffer_wipe_n/Makefile
  tests/cbmc/proofs/s2n_stuffer_wipe_n/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_wipe_n/s2n_stuffer_wipe_n_harness.c
Labels: type/formal_verification, type/test

#1430 Remove duplicated signature algorithm values sent from client
  tls/s2n_signature_scheme.c
Labels: type/tls_1.3

#1426 Verify server certificate only after negotiating signature scheme
  tests/unit/s2n_server_cert_verify_test.c
  tls/s2n_server_cert_verify.c
Labels: type/tls_1.3

#1457 Use correct handshake hash for generating Certificate Verify content
  tests/unit/s2n_server_cert_verify_test.c
  tls/s2n_server_cert_verify.c
Labels: type/tls_1.3

#1425 Adding BIKE_R2
  CMakeLists.txt
  lib/Makefile
  pq-crypto/Makefile
  pq-crypto/bike_r2/LICENSE
  pq-crypto/bike_r2/Makefile
  pq-crypto/bike_r2/README.md
  pq-crypto/bike_r2/aes_ctr_prf.c
  pq-crypto/bike_r2/aes_ctr_prf.h
  pq-crypto/bike_r2/aes_wrap.h
  pq-crypto/bike_r2/bike_defs.h
  pq-crypto/bike_r2/bike_r2_kem.c
  pq-crypto/bike_r2/bike_r2_kem.h
  pq-crypto/bike_r2/cleanup.h
  pq-crypto/bike_r2/decode.c
  pq-crypto/bike_r2/decode.h
  pq-crypto/bike_r2/defs.h
  pq-crypto/bike_r2/error.c
  pq-crypto/bike_r2/error.h
  pq-crypto/bike_r2/functions_renaming.h
  pq-crypto/bike_r2/gf2x.h
  pq-crypto/bike_r2/gf2x_internal.h
  pq-crypto/bike_r2/gf2x_mul.c
  pq-crypto/bike_r2/gf2x_portable.c
  pq-crypto/bike_r2/openssl_utils.c
  pq-crypto/bike_r2/openssl_utils.h
  pq-crypto/bike_r2/parallel_hash.c
  pq-crypto/bike_r2/parallel_hash.h
  pq-crypto/bike_r2/sampling.c
  pq-crypto/bike_r2/sampling.h
  pq-crypto/bike_r2/sampling_portable.c
  pq-crypto/bike_r2/secure_decode_portable.c
  pq-crypto/bike_r2/sha.h
  pq-crypto/bike_r2/types.h
  pq-crypto/bike_r2/utilities.c
  pq-crypto/bike_r2/utilities.h
  tests/unit/kats/bike_r2.kat
  tests/unit/s2n_bike_r2_kat_test.c
  tests/unit/s2n_bike_r2_test.c
  tls/s2n_kem.c
  tls/s2n_kem.h
  tls/s2n_tls_parameters.h
Labels: type/post-quantum

#1467 Make SIKE file/symbol naming (more) consistent
  .travis.yml
  CMakeLists.txt
  pq-crypto/README.md
  pq-crypto/sike_r1/Makefile
  pq-crypto/sike_r1/sike_r1_kem.c
  pq-crypto/sike_r1/sike_r1_kem.h
  pq-crypto/sike_r2/P434.c
  pq-crypto/sike_r2/sike_r2_kem.c
  pq-crypto/sike_r2/sike_r2_kem.h
  tests/fuzz/s2n_hybrid_ecdhe_sike_r1_fuzz_test.c
  tests/fuzz/s2n_sike_r1_fuzz_test.c
  tests/fuzz/s2n_sike_r2_fuzz_test.c
  tests/unit/kats/bike_r1.kat
  tests/unit/kats/bike_r2.kat
  tests/unit/kats/hybrid_ecdhe_sike_r1.kat
  tests/unit/kats/sike_r1.kat
  tests/unit/kats/sike_r2.kat
  tests/unit/s2n_hybrid_ecdhe_sike_r1.c
  tests/unit/s2n_sike_r1_kat_test.c
  tests/unit/s2n_sike_r1_kem_test.c
  tests/unit/s2n_sike_r2_kat_test.c
  tls/s2n_kem.c
  tls/s2n_tls_parameters.h
Labels: type/post-quantum

#1449 Add tls13 integration tests
  tests/integration/Makefile
  tests/integration/common/__init__.py
  tests/integration/common/s2n_test_common.py
  tests/integration/common/s2n_test_openssl.py
  tests/integration/common/s2n_test_reporting.py
  tests/integration/common/s2n_test_scenario.py
  tests/integration/s2n_tls13_handshake_tests.py
Labels: type/tls_1.3

#1472 Fuzz Test Fixes
  tests/fuzz/s2n_bike_r1_fuzz_test.c
  tests/fuzz/s2n_client_cert_recv_test.c
  tests/fuzz/s2n_client_cert_req_recv_test.c
  tests/fuzz/s2n_client_cert_verify_recv_test.c
  tests/fuzz/s2n_client_fuzz_test.c
  tests/fuzz/s2n_client_hello_recv_fuzz_test.c
  tests/fuzz/s2n_client_key_recv_fuzz_test.c
  tests/fuzz/s2n_encrypted_extensions_recv_test.c
  tests/fuzz/s2n_extensions_client_key_share_recv_test.c
  tests/fuzz/s2n_extensions_client_supported_versions_recv_test.c
  tests/fuzz/s2n_extensions_server_key_share_recv_test.c
  tests/fuzz/s2n_extensions_server_supported_versions_recv_test.c
  tests/fuzz/s2n_hybrid_ecdhe_sike_r1_fuzz_test.c
  tests/fuzz/s2n_openssl_diff_pem_parsing_test.c
  tests/fuzz/s2n_select_server_cert_test.c
  tests/fuzz/s2n_server_extensions_recv_test.c
  tests/fuzz/s2n_server_fuzz_test.c
  tests/fuzz/s2n_sike_r1_fuzz_test.c
  tests/fuzz/s2n_sike_r2_fuzz_test.c
  tests/fuzz/s2n_stuffer_pem_fuzz_test.c
Labels: type/fuzz_test
