Repository aws/s2n-tls, pull requests merged in 2020-10, with the labels that each got.

#2291 Improves slow s2n_stuffer CBMC-proofs
  stuffer/s2n_stuffer.c
  tests/cbmc/proofs/s2n_stuffer_writev_bytes/Makefile
  tests/cbmc/stubs/memcpy_havoc.c
Labels: CBMC

#2322 Adding underflow checks
  tests/sidetrail/DEBUGGING.md
  tests/sidetrail/README.md
  tests/sidetrail/working/s2n-record-read-cbc-negative-test/copy_as_needed.sh
  tests/sidetrail/working/s2n-record-read-cbc-negative-test/record_read_cbc.patch
  tests/sidetrail/working/s2n-record-read-cbc/copy_as_needed.sh
  tests/sidetrail/working/s2n-record-read-cbc/record_read_cbc.patch
  tests/sidetrail/working/s2n-record-read-composite/copy_as_needed.sh
  tests/sidetrail/working/s2n-record-read-composite/record_read.patch
  tls/s2n_record_read_cbc.c
  tls/s2n_record_read_composite.c
Labels: ops-backlog

#2324 Fix typo edx->ebx in SIKE asm check
  pq-crypto/sike_r2/P434.c
Labels: type/post-quantum

#2031 Adds --pointer-primitive-check flag on CBMC proofs
  stuffer/s2n_stuffer.c
  stuffer/s2n_stuffer_text.c
  tests/cbmc/proofs/Makefile-project-defines
  tests/cbmc/proofs/s2n_pkcs3_to_dh_params/Makefile
  tests/cbmc/proofs/s2n_stuffer_peek_check_for_str/s2n_stuffer_peek_check_for_str_harness.c
  tests/cbmc/proofs/s2n_stuffer_read_expected_str/s2n_stuffer_read_expected_str_harness.c
  tests/cbmc/proofs/s2n_stuffer_skip_read_until/s2n_stuffer_skip_read_until_harness.c
  tests/cbmc/proofs/s2n_stuffer_writev_bytes/s2n_stuffer_writev_bytes_harness.c
  tests/cbmc/sources/proof_allocators.c
Labels: CBMC

#2351 Add pq-crypto/ to cppcheck
  codebuild/bin/cppcheck_suppressions.txt
  codebuild/bin/run_cppcheck.sh
  pq-crypto/bike_r1/aes_wrap.h
  pq-crypto/bike_r1/gf2x_portable.c
  pq-crypto/bike_r1/openssl_utils.c
  pq-crypto/bike_r1/sampling.c
  pq-crypto/bike_r1/sampling_portable.c
  pq-crypto/bike_r2/aes_wrap.h
  pq-crypto/bike_r2/gf2x_portable.c
  pq-crypto/bike_r2/openssl_utils.c
  pq-crypto/bike_r2/sampling.c
  pq-crypto/bike_r2/sampling_portable.c
  pq-crypto/kyber_90s_r2/aes256ctr.c
  pq-crypto/kyber_90s_r2/aes_c.c
  pq-crypto/kyber_90s_r2/cbd.c
  pq-crypto/kyber_90s_r2/indcpa.c
  pq-crypto/kyber_90s_r2/poly.c
  pq-crypto/kyber_90s_r2/sha2_c.c
  pq-crypto/kyber_r2/cbd.c
  pq-crypto/kyber_r2/fips202_kyber_r2.c
  pq-crypto/kyber_r2/indcpa.c
  pq-crypto/kyber_r2/poly.c
  pq-crypto/sike_r1/ec_isogeny_r1.c
  pq-crypto/sike_r1/fips202_r1.c
  pq-crypto/sike_r1/fp_generic_r1.c
  pq-crypto/sike_r1/sike_r1_kem.c
  pq-crypto/sike_r2/ec_isogeny.c
  pq-crypto/sike_r2/fips202.c
  pq-crypto/sike_r2/fp.c
  pq-crypto/sike_r2/fpx.c
  pq-crypto/sike_r2/sike_r2_kem.c
  tests/saw/sike_r1/patch/ec_isogeny_r1.c.patch
  tests/saw/sike_r2/patch/ec_isogeny.c.patch
Labels: type/post-quantum
