Repository aws/s2n-tls, pull requests merged in 2020-02, with the labels that each got.

#1481 Add Server Certificate selection for TLS 1.3
  error/s2n_errno.c
  error/s2n_errno.h
  tests/integration/Makefile
  tests/unit/s2n_tls13_handshake_test.c
  tests/unit/s2n_tls13_server_cert_selection_test.c
  tls/s2n_cipher_suites.c
  tls/s2n_cipher_suites.h
  tls/s2n_client_hello.c
  tls/s2n_server_cert.c
  tls/s2n_signature_algorithms.c
  tls/s2n_signature_algorithms.h
  tls/s2n_signature_scheme.c
  tls/s2n_signature_scheme.h
Labels: type/tls_1.3

#1535 Fuzz Test Coverage Reporting
  .travis.yml
  .travis/s2n_after_travis_build.sh
  codebuild/bin/install_clang.sh
  codebuild/bin/s2n_after_codebuild.sh
  codebuild/bin/s2n_codebuild.sh
  codebuild/bin/s2n_setup_env.sh
  codebuild/codebuild.config
  codebuild/spec/buildspec_ubuntu.yml
  coverage/Makefile
  lib/Makefile
  s2n.mk
  tests/fuzz/Makefile
  tests/fuzz/Readme.md
  tests/fuzz/calcTotalCov.sh
  tests/fuzz/runFuzzTest.sh
  tests/fuzz/s2n_bike_r1_fuzz_test.c
  tests/fuzz/s2n_certificate_extensions_parse_test.c
  tests/fuzz/s2n_client_cert_recv_test.c
  tests/fuzz/s2n_client_cert_req_recv_test.c
  tests/fuzz/s2n_client_cert_verify_recv_test.c
  tests/fuzz/s2n_client_fuzz_test.c
  tests/fuzz/s2n_client_hello_recv_fuzz_test.c
  tests/fuzz/s2n_client_key_recv_fuzz_test.c
  tests/fuzz/s2n_encrypted_extensions_recv_test.c
  tests/fuzz/s2n_extensions_client_key_share_recv_test.c
  tests/fuzz/s2n_extensions_client_supported_versions_recv_test.c
  tests/fuzz/s2n_extensions_server_key_share_recv_test.c
  tests/fuzz/s2n_extensions_server_supported_versions_recv_test.c
  tests/fuzz/s2n_hybrid_ecdhe_sike_r1_fuzz_test.c
  tests/fuzz/s2n_openssl_diff_pem_parsing_test.c
  tests/fuzz/s2n_recv_client_supported_groups_test.c
  tests/fuzz/s2n_select_server_cert_test.c
  tests/fuzz/s2n_server_extensions_recv_test.c
  tests/fuzz/s2n_server_fuzz_test.c
  tests/fuzz/s2n_sike_r1_fuzz_test.c
  tests/fuzz/s2n_sike_r2_fuzz_test.c
  tests/fuzz/s2n_stuffer_pem_fuzz_test.c
Labels: type/code_coverage, type/fuzz_test

#1470 Adds SIKE R2 KEM test
  tests/unit/s2n_sike_r2_kem_test.c
Labels: type/post-quantum

#1473 Add fuzz test for standalone BIKE round 2
  tests/fuzz/corpus/s2n_bike_r1_fuzz_test/0712f74e6f115ca892244e6189dea3c59521a3fb
  tests/fuzz/corpus/s2n_bike_r2_fuzz_test/0a9133f1142a80fbe0a67c3673a0c4713f231e95
  tests/fuzz/corpus/s2n_bike_r2_fuzz_test/14ba7e9c49311c5da8957b478524540d45fa0497
  tests/fuzz/corpus/s2n_bike_r2_fuzz_test/1aca07cde33e30c73798015e22c0aea77a1c42b1
  tests/fuzz/corpus/s2n_bike_r2_fuzz_test/29b670942369944f233ba9ef0ac7047aefc9d1dd
  tests/fuzz/corpus/s2n_bike_r2_fuzz_test/4345cb1fa27885a8fbfe7c0c830a592cc76a552b
  tests/fuzz/corpus/s2n_bike_r2_fuzz_test/5a9642041cb29927da92da7cc282c8a38eaab001
  tests/fuzz/corpus/s2n_bike_r2_fuzz_test/6b8b16cdbc2774d78bb0f667c2171ab17b77cc6f
  tests/fuzz/corpus/s2n_bike_r2_fuzz_test/821e5c9585a39c963ba8b44aa2ee1b7de114d573
  tests/fuzz/corpus/s2n_bike_r2_fuzz_test/82c452e8fdf902ce6028888a904b73afe6f5e83e
  tests/fuzz/corpus/s2n_bike_r2_fuzz_test/fa3be0eb738747f26365e46e1c7898e14dff7e09
  tests/fuzz/corpus/s2n_bike_r2_fuzz_test/fd0ae3e4936cb109d7913af34cc95cfae7f2169c
  tests/fuzz/corpus/s2n_bike_r2_fuzz_test/valid_ciphertext
  tests/fuzz/s2n_bike_r2_fuzz_test.c
  tests/unit/s2n_bike_r1_kem_test.c
  tests/unit/s2n_bike_r2_kem_test.c
Labels: type/post-quantum

#1480 Adds BIKE round 2 hybrid PRF test vectors
  tests/unit/kats/hybrid_prf.kat
  tests/unit/s2n_tls_hybrid_prf_test.c
Labels: type/post-quantum

#1550 Enabled TLS 1.3 Handshake Test Features
  tests/unit/s2n_tls13_handshake_test.c
Labels: type/tls_1.3

#1506 try_compile PQ ASM code before including it in build
  CMakeLists.txt
  pq-crypto/README.md
  pq-crypto/sike_r2/Makefile
  tests/unit/Makefile
  tests/unit/s2n_pq_asm_noop_test.c
Labels: type/post-quantum

#1527 Update BIKE R2 code to match the latest code and BIKE's v3.2 specification
  pq-crypto/bike_r2/aes_ctr_prf.h
  pq-crypto/bike_r2/aes_wrap.h
  pq-crypto/bike_r2/bike_r2_kem.c
  pq-crypto/bike_r2/cleanup.h
  pq-crypto/bike_r2/decode.h
  pq-crypto/bike_r2/defs.h
  pq-crypto/bike_r2/functions_renaming.h
  pq-crypto/bike_r2/gf2x_internal.h
  pq-crypto/bike_r2/gf2x_mul.c
  pq-crypto/bike_r2/gf2x_portable.c
  pq-crypto/bike_r2/parallel_hash.c
  pq-crypto/bike_r2/parallel_hash.h
  pq-crypto/bike_r2/sampling.c
  pq-crypto/bike_r2/sampling.h
  pq-crypto/bike_r2/secure_decode_portable.c
  pq-crypto/bike_r2/sha.h
  pq-crypto/bike_r2/types.h
  pq-crypto/bike_r2/utilities.h
  tests/unit/kats/bike_r2.kat
Labels: type/post-quantum

#1394 Add CBMC Proof of s2n_stuffer_read()
  tests/cbmc/proofs/s2n_stuffer_read/Makefile
  tests/cbmc/proofs/s2n_stuffer_read/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_read/s2n_stuffer_read_harness.c
Labels: CBMC

#1400 Mww/alloc
  tests/cbmc/proofs/s2n_stuffer_alloc/Makefile
  tests/cbmc/proofs/s2n_stuffer_alloc/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_alloc/s2n_stuffer_alloc_harness.c
Labels: CBMC

#1401 Add CBMC Proof of s2n_stuffer_erase_and_read_bytes()
  tests/cbmc/proofs/s2n_stuffer_erase_and_read_bytes/Makefile
  tests/cbmc/proofs/s2n_stuffer_erase_and_read_bytes/cbmc-batch.yaml
  tests/cbmc/proofs/s2n_stuffer_erase_and_read_bytes/s2n_stuffer_erase_and_read_bytes_harness.c
Labels: CBMC

#1561 Adds BIKE R2 hybrid ECDHE KAT and fuzz tests
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r2_fuzz_test/0e356ba505631fbf715758bed27d503f8b260e3a
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r2_fuzz_test/2c0267ad233a9eb95da8376c400348d9fc9edf4b
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r2_fuzz_test/40e4cc218b105a4022842fd95c4a1d189890ea6e
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r2_fuzz_test/56bf04dbcfed7e109dbc4f1ca459e3b12908c06d
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r2_fuzz_test/5ba93c9db0cff93f52b521d7420e43f6eda2784f
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r2_fuzz_test/c2204edbfb1b72c9e996a5e6464f6ab0198c494f
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r2_fuzz_test/valid_client
  tests/fuzz/s2n_hybrid_ecdhe_bike_r2_fuzz_test.c
  tests/unit/kats/hybrid_ecdhe_bike_r2.kat
  tests/unit/s2n_hybrid_ecdhe_bike_r2_test.c
Labels: type/post-quantum

#1559 Add cipher preference for SIKE round 2 testing
  tests/unit/s2n_cipher_preference_test.c
  tests/unit/s2n_kem_test.c
  tls/s2n_cipher_preferences.c
  tls/s2n_cipher_preferences.h
  tls/s2n_cipher_suites.c
Labels: type/post-quantum

#1560 Adds SIKE R2 hybrid ECDHE fuzz and KAT tests
  tests/fuzz/corpus/s2n_hybrid_ecdhe_sike_r2_fuzz_test/5335b312ce2c43d5a2b34a38367a6f9ef44a6df0
  tests/fuzz/corpus/s2n_hybrid_ecdhe_sike_r2_fuzz_test/5ae372909f1a42f175008a597044c219e4e67dfd
  tests/fuzz/corpus/s2n_hybrid_ecdhe_sike_r2_fuzz_test/5ba93c9db0cff93f52b521d7420e43f6eda2784f
  tests/fuzz/corpus/s2n_hybrid_ecdhe_sike_r2_fuzz_test/a70fb6a9415d3c34a9ea5510ba7e3a055d88aef9
  tests/fuzz/corpus/s2n_hybrid_ecdhe_sike_r2_fuzz_test/de48cb8de8cae19995555564dfa285dfbd046977
  tests/fuzz/corpus/s2n_hybrid_ecdhe_sike_r2_fuzz_test/valid_client_key_exchange_message
  tests/fuzz/s2n_hybrid_ecdhe_sike_r2_fuzz_test.c
  tests/unit/kats/hybrid_ecdhe_sike_r1.kat
  tests/unit/kats/hybrid_ecdhe_sike_r2.kat
  tests/unit/s2n_hybrid_ecdhe_sike_r2_test.c
Labels: type/post-quantum

#1564 Add BIKE R1 hybrid ECDHE KAT and fuzz tests
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/1046f2b3eed73beb6c3b2c463f4660d7faabaffb
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/1b5f0925bcd4c4bf22376484b40ff0e6077724bf
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/23b30d12feeff3e2e37fbf2b2c3098c3fff91421
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/243e205fc39f5d5382bda2a63617da1574fe1d09
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/3000dfd0b78c29be632db6a718177d2dc362081e
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/388dcc716d8057f31c7c4635b6a91842099e5117
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/3ae113b886209d039086bf6562483ab8527e8b0a
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/447f8fcd1b5503f6108fb7861c85cbadecedbab9
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/7e15297a42ccc5fcfa813d53e25a536d23d39fb5
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/850a52ade181e3178f7bc60a6165658899c57e3c
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/8c6f2f74b255a66ecd3ee39e2d496e83e4306cc3
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/983938ab7a450bdc2872122cdddb1ea77978df13
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/991fc8d1aed96dd8fe604e8f11f317b9c6157aaa
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/9cde9cbf82ca737a934f7b2a2a5aad9755893152
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/bfac137a955fb798f1ed6556cd5e6faae19476d6
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/c98f46ec94a59f1587023f7b4f796012f7c8615c
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/d699c11b42e27b746f565c0eabf18ae1a78853ad
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/d7eb3ca70c7709823a277742d7a46de8bd2f37d5
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/da35b51f5f3e9f565ed31da9de22134c3f0ad6e7
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/f1cb6129661666a9808574cab39c39780b548ce2
  tests/fuzz/corpus/s2n_hybrid_ecdhe_bike_r1_fuzz_test/valid_client_exchange
  tests/fuzz/s2n_hybrid_ecdhe_bike_r1_fuzz_test.c
  tests/unit/kats/hybrid_ecdhe_bike_r1.kat
  tests/unit/s2n_hybrid_ecdhe_bike_r1_test.c
Labels: type/post-quantum
