Repository aws/s2n-tls, pull requests merged in 2021-07, with the labels that each got.

#2842 Add Round 3 PQ TLS Policies
  tests/unit/s2n_client_key_share_extension_pq_test.c
  tests/unit/s2n_kex_with_kem_test.c
  tests/unit/s2n_security_policies_test.c
  tests/unit/s2n_server_key_share_extension_test.c
  tests/unit/s2n_tls13_hybrid_shared_secret_test.c
  tests/unit/s2n_tls13_pq_handshake_test.c
  tls/s2n_cipher_preferences.c
  tls/s2n_cipher_preferences.h
  tls/s2n_kem.c
  tls/s2n_kem.h
  tls/s2n_kem_preferences.c
  tls/s2n_kem_preferences.h
  tls/s2n_security_policies.c
  tls/s2n_security_policies.h
  tls/s2n_tls_parameters.h
Labels: type/post-quantum

#2936 Add Round 3 PQ Hybrid TLS 1.3 Known Answer Tests
  tests/unit/kats/generate_pq_hybrid_tls13_handshake_kats.py
  tests/unit/s2n_tls13_hybrid_shared_secret_test.c
Labels: type/post-quantum

#2847 Adds proofs for s2n_handshake_io functions
  tests/cbmc/proofs/s2n_connection_get_last_message_name/Makefile
  tests/cbmc/proofs/s2n_connection_get_last_message_name/cbmc-proof.txt
  tests/cbmc/proofs/s2n_connection_get_last_message_name/s2n_connection_get_last_message_name_harness.c
  tests/cbmc/proofs/s2n_is_hello_retry_handshake/Makefile
  tests/cbmc/proofs/s2n_is_hello_retry_handshake/cbmc-proof.txt
  tests/cbmc/proofs/s2n_is_hello_retry_handshake/s2n_is_hello_retry_handshake_harness.c
  tests/cbmc/proofs/s2n_is_hello_retry_message/Makefile
  tests/cbmc/proofs/s2n_is_hello_retry_message/cbmc-proof.txt
  tests/cbmc/proofs/s2n_is_hello_retry_message/s2n_is_hello_retry_message_harness.c
  tls/s2n_handshake.c
  tls/s2n_handshake.h
  tls/s2n_handshake_io.c
  tls/s2n_handshake_type.c
Labels: CBMC

#2974 Fix compatibility issues with PQ TLS 1.3 Security Policies found during integration testing
  tests/unit/s2n_kex_with_kem_test.c
  tests/unit/s2n_security_policies_test.c
  tests/unit/s2n_tls13_pq_handshake_test.c
  tls/s2n_cipher_preferences.c
  tls/s2n_cipher_preferences.h
  tls/s2n_security_policies.c
  tls/s2n_security_policies.h
Labels: type/post-quantum

#2976 ci: CodeBuild arm unit test
  codebuild/spec/buildspec_omnibus.yml
Labels: type/codebuild

#2978 Add new Security Policies for AWS Common Runtime SDKs
  tests/unit/s2n_security_policies_test.c
  tls/s2n_cipher_preferences.c
  tls/s2n_cipher_preferences.h
  tls/s2n_security_policies.c
  tls/s2n_security_policies.h
Labels: type/tls_1.3

#2979 Added Method to Retrieve Digest for EMS
  tests/unit/s2n_tls_prf_test.c
  tls/s2n_prf.c
  tls/s2n_prf.h
Labels: EMS
