Repository aws/s2n-tls, pull requests merged in 2025-07, with the labels that each got.

#5386 chore: apply clippy and fmt fixes
  bindings/rust/extended/s2n-tls-sys/build.rs
  bindings/rust/extended/s2n-tls-sys/tests/s2n_init.rs
  bindings/rust/extended/s2n-tls-tokio/tests/common/mod.rs
  bindings/rust/extended/s2n-tls/src/error.rs
  bindings/rust/extended/s2n-tls/src/testing.rs
  tests/pcap/build.rs
  tests/pcap/src/handshake_message.rs
  tests/pcap/src/lib.rs
  tests/pcap/tests/s2n_client_hellos.rs
Labels: s2n-core

#5375 feature: new TLS1.2 + FIPS CRT security policy
  tests/policy_snapshot/snapshots/AWS-CRT-SDK-TLSv1.2-2025
  tls/s2n_cipher_preferences.c
  tls/s2n_cipher_preferences.h
  tls/s2n_security_policies.c
Labels: s2n-core

#5397 chore: release 0.3.22
  bindings/rust/extended/s2n-tls-sys/Cargo.toml
  bindings/rust/extended/s2n-tls-sys/templates/Cargo.template
  bindings/rust/extended/s2n-tls-tokio/Cargo.toml
  bindings/rust/extended/s2n-tls/Cargo.toml
  bindings/rust/standard/s2n-tls-hyper/Cargo.toml
Labels: s2n-core

#5370 docs: note that s2n_shutdown may keep reading
  docs/usage-guide/topics/ch07-io.md
Labels: s2n-core

#5398 feat(aws-kms-tls-auth): add codec and parsing
  .github/workflows/ci_aws_kms_tls_auth.yml
  bindings/rust/aws-kms-tls-auth/Cargo.toml
  bindings/rust/aws-kms-tls-auth/fuzz/.gitignore
  bindings/rust/aws-kms-tls-auth/fuzz/Cargo.toml
  bindings/rust/aws-kms-tls-auth/fuzz/README.md
  bindings/rust/aws-kms-tls-auth/fuzz/fuzz_targets/psk_client_hello.rs
  bindings/rust/aws-kms-tls-auth/src/codec.rs
  bindings/rust/aws-kms-tls-auth/src/lib.rs
  bindings/rust/aws-kms-tls-auth/src/prefixed_list.rs
  bindings/rust/aws-kms-tls-auth/src/psk_parser.rs
Labels: s2n-core

#5383 ci: start codebuild jobs from github actions
  .github/workflows/ci_linting.yml
  .github/workflows/codebuild.yml
  codebuild/bin/start_codebuild.sh
Labels: s2n-core

#5400 ci: Migrate Duvet GitHub Action to duvet-action repo
  .github/workflows/ci_compliance.yml
Labels: s2n-core

#5402 feat(aws-kms-tls-auth): add psk identity
  bindings/rust/aws-kms-tls-auth/resources/psk_identity.bin
  bindings/rust/aws-kms-tls-auth/src/identity.rs
  bindings/rust/aws-kms-tls-auth/src/lib.rs
  bindings/rust/aws-kms-tls-auth/src/prefixed_list.rs
Labels: s2n-core

#5352 Flip Nix integration tests to use uv/pytest
  codebuild/spec/buildspec_integv2_nix.yml
  nix/shell.sh
  tests/integrationv2/uvinteg_tests.txt
Labels: type/nix

#5408 feat(aws-kms-tls-auth): add provider & receiver structs
  bindings/rust/aws-kms-tls-auth/Cargo.toml
  bindings/rust/aws-kms-tls-auth/resources/psk_identity.bin
  bindings/rust/aws-kms-tls-auth/src/codec.rs
  bindings/rust/aws-kms-tls-auth/src/identity.rs
  bindings/rust/aws-kms-tls-auth/src/lib.rs
  bindings/rust/aws-kms-tls-auth/src/prefixed_list.rs
  bindings/rust/aws-kms-tls-auth/src/provider.rs
  bindings/rust/aws-kms-tls-auth/src/receiver.rs
  bindings/rust/aws-kms-tls-auth/src/test_utils.rs
Labels: s2n-core

#5409 docs(aws-kms-tls-auth): add readme
  bindings/rust/aws-kms-tls-auth/DEVELOPMENT.md
  bindings/rust/aws-kms-tls-auth/README.md
  bindings/rust/aws-kms-tls-auth/src/lib.rs
Labels: s2n-core

#5333 ci: run rustfmt/clippy on standard crates
  .github/workflows/ci_rust.yml
  bindings/rust/standard/bench/benches/handshake.rs
  bindings/rust/standard/bench/benches/resumption.rs
  bindings/rust/standard/bench/benches/throughput.rs
  bindings/rust/standard/bench/src/rustls.rs
  bindings/rust/standard/integration/src/features/mldsa.rs
  bindings/rust/standard/integration/src/network/tls_client.rs
  bindings/rust/standard/s2n-tls-hyper/src/error.rs
  bindings/rust/standard/s2n-tls-hyper/tests/http.rs
Labels: s2n-core

#5395 feat: add secp384r1_mlkem_1024 kem group
  tests/policy_snapshot/snapshots/test_all
  tests/unit/kats/generate_pq_hybrid_tls13_handshake_kats.py
  tests/unit/s2n_kem_preferences_test.c
  tests/unit/s2n_tls13_hybrid_shared_secret_test.c
  tests/unit/s2n_tls13_pq_handshake_test.c
  tls/s2n_kem.c
  tls/s2n_kem.h
  tls/s2n_tls_parameters.h
Labels: s2n-core

#5427 chore: Nix Corretto version bump/upstream
  flake.lock
  flake.nix
  nix/amazon-corretto-17.nix
Labels: s2n-core, type/nix

#5434 refactor(bench): unify IO methods
  bindings/rust/standard/bench/src/harness/io.rs
  bindings/rust/standard/bench/src/harness/mod.rs
  bindings/rust/standard/bench/src/lib.rs
  bindings/rust/standard/bench/src/openssl.rs
  bindings/rust/standard/bench/src/rustls.rs
  bindings/rust/standard/bench/src/s2n_tls.rs
  bindings/rust/standard/bench/src/test_utilities.rs
Labels: s2n-core

#5441 ci: document how to manually run the codebuild jobs
  .github/workflows/codebuild.yml
Labels: s2n-core

#5445 fix(typo): fix a typo in codebuild.yml
  .github/workflows/codebuild.yml
Labels: s2n-core

#5450 chore(ci): tell crt to not check submodule version
  codebuild/bin/build_aws_crt_cpp.sh
Labels: s2n-core
